#!/usr/bin/env python

def build(bld):
	prog = bld(features='cc cprogram')
	# symbolic name used to reference this object
	prog.name = 'sloc.program'
	#prog.includes  = '/usr/include'
	# name of the resulting program
	prog.target = 'sloc'
	prog.source = 'main.vala  aboutdialog.vala  project.vala sloc.vala'
	# libraries to link against
	prog.uselib = 'GTK+ GEE GLIB '
	# Vala packages to use
	prog.packages = 'gtk+-3.0 gee-1.0 glib-2.0'
	# Extra vapi dirs
	#prog.vapi_dirs = '../my_lib'
	# Enable threading
	prog.threading = True
